include include_top.mac

INCLUDES   = ${INCLUDES_COMMON}
CFLAGS     = ${CFLAGS_COMMON} ${INCLUDES} -DNDEBUG -DGL_SILENCE_DEPRECATION
LDFLAGS    = ${LDFLAGS_COMMON}
EXECUTABLE = ../bin/simulator

SOURCES    = simulator.cpp \
						 Grid/StaggeredGrid.cpp \
						 util/GaussianBlur.cpp \
						 util/ReadPPM.cpp \
						 Watercolor2D.cpp \
						 FIELD_2D.cpp 

include include_bottom.mk
